Add CI job allowing collection build and publish

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,8 @@ variables:
 
 stages:
 - tests
+- build
+- publish
 
 
 sanity:
@@ -33,3 +35,35 @@ integration:
 #  script:
 #    - ansible --version
 #    - ansible-test units --python 3.6
+
+build collection:
+  stage: build
+  before_script:
+    - yum update -y && yum install -y python3 openssh-clients git
+    - pip3 install -r requirements.txt
+    - mkdir artefact/
+  script:
+    - ansible --version
+    - ansible-galaxy collection build --output-path artefact/
+  artifacts:
+    paths:
+    - artefact/
+    expire_in: 1 day
+
+publish collection:
+  stage: build
+  before_script:
+    - yum update -y && yum install -y python3 openssh-clients git
+    - pip3 install -r requirements.txt
+  variables:
+    COLLECTION_PATH: "artefact/sfr-harbor-${CI_COMMIT_TAG}.tar.gz"
+    NEXUS_COLLECTION_PATH: "valentine/ansible_collections"
+  script:
+    - |
+      if [ ! -f "${COLLECTION_PATH}" ]; then
+          echo "Collection $COLLECTION_PATH archive not found, did you update the galaxy.yml with the proper version?" 
+          exit 1
+      fi
+    - curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file ${COLLECTION_PATH} $NEXUS_REPO/$NEXUS_COLLECTION_PATH/sfr-harbor-${CI_COMMIT_TAG}.tar.gz
+  only:
+    - tags
